travis:
  secure:
    BINSTAR_TOKEN: Z838yMVV80Db+iEdSfBVEDwYNDVYh1kfx8EgqOrC2NlfFD7RKtXaojzlGCanPEI6At8EPQyxCpEB2br0iXFesBgaNYNgdOD+T+tznsL0GFpE7tW8NLxHfhMZf7gv5cjSCtnGtDEPKKx+YG/PF1aTIRjK1MaVsNKeEPeuYHCwLXfEY6ztLuobh4xLMxZaDOAD7Egwy7kXbqoiveU8hoWBDENjeYns5lAOuXzhv3skUSXoegMT59D1h8jcRvnA6HjI2YPzu2gz1vPQa2EFIFB5b76DzDWzy0mnYT71jQPfiqCZU9u+CELUPm4xa/owbjivPE1w0fGnOGNBJ6lYD3L+PZSjqMU+UzPebGBeyiVfr6Q2bYO4BCz+4ZKq4fRuosffjs56qm8mh/KSuKCPAa+GpZ2UDWNvxA4YBozIkjrmuH1Zs7upCj+aJicIhUzSU8kt/ETNktHcGLhhYr6jbsGppG/YhTnNTQxm0QgNOsDBgqIcBoiaFDf75MZdSHkfm7r/hHA17MZ9OBfgfEWeb7nH3HfSSIWZyeU37sDgUaHejLjOwLzP5cVlrALyqBsvjyRG/cqaE735WSaDwBkrEipqE/d08NF/hR/wB3EuyM8j6A8uiuSDEh7gKP5ajhuCcahyZwxd6GOkoR3a2N+dWzINWCUh3cheUNGMDkXHx2LoEe0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
